---
abstract: 'A bot for IRC New Years parties'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-IRCBot-NewYears
requires:
  Data::Dumper: 0
  Date::Manip: 6.36
  DateTime: 1.03
  Encode: 2.55
  Number::Denominal: 1.104
  POE: 1.354
  POE::Component::IRC: 6.83
  POE::Component::IRC::Plugin::BotAddressed: 6.83
  POE::Component::IRC::Plugin::Connector: 6.83
  POE::Component::IRC::Plugin::WWW::Google::Time: 0.0102
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/App-IRCBot-NewYears/issues
  repository: git://github.com/zoffixznet/App-IRCBot-NewYears.git
version: 1.001003
