---
abstract: 'A bot for IRC New Years parties'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-IRCBot-NewYears
provides:
  App::IRCBot::NewYears:
    file: lib/App/IRCBot/NewYears.pm
    version: 1.001001
requires:
  Data::Dumper: 2.136
  Date::Manip: 6.36
  DateTime: 1.03
  Encode: 2.55
  Number::Denominal: 1.102
  POE: 1.354
  POE::Component::IRC: 6.83
  POE::Component::IRC::Plugin::BotAddressed: 6.83
  POE::Component::IRC::Plugin::Connector: 6.83
  POE::Component::IRC::Plugin::WWW::Google::Time: 0.0102
  perl: 5.010
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.001001
